import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo
import kotlin.reflect.KClass

class KotlinXSerializableProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
    private val namespace: String
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val targetAnnotation = "kotlinx.serialization.Serializable"
        val symbols = resolver.getSymbolsWithAnnotation(targetAnnotation)
        logger.info("KotlinXSerializableProcessor: scanning symbols annotated with $targetAnnotation")

        val validClasses = symbols
            .filterIsInstance<KSClassDeclaration>()
            .filter { it.validate() }
            .toList()
        val deferredSymbols = symbols.filter { !it.validate() }.toList()

        logger.info(
            "KotlinXSerializableProcessor: found ${validClasses.size} valid serializable classes" +
                    if (deferredSymbols.isNotEmpty()) {
                        "; deferring ${deferredSymbols.size} symbols"
                    } else {
                        ""
                    }
        )

        if (validClasses.isNotEmpty()) {
            generateReflectionFeature(validClasses)
        } else {
            logger.info("KotlinXSerializableProcessor: no valid serializable classes found; skipping generation")
        }

        return deferredSymbols
    }

    private fun generateReflectionFeature(classes: List<KSClassDeclaration>) {
        val packageName = namespace
        val fileName = "KotlinXSerializableClasses"

        // Format the class reference list (e.g. listOf(Greeting::class, Greeting2::class))
        val classListCode = classes.joinToString(", ") { "%T::class" }
        val classTypeArgs = classes.map { it.toClassName() }.toTypedArray()

        val fileSpec =
            FileSpec.builder(packageName, fileName)
                .addType(
                    TypeSpec.objectBuilder("KotlinXSerializableClasses")
                        .addProperty(
                            PropertySpec.builder(
                                "classes",
                                List::class.asClassName().parameterizedBy(
                                    KClass::class.asClassName().parameterizedBy(STAR)
                                )
                            )
                                .initializer(
                                    "listOf($classListCode)",
                                    *classTypeArgs
                                )
                                .addKdoc("List of all serializable classes found by the processor")
                                .build()
                        )
                        .build()

                )
                .addFileComment("Generated by KotlinXSerializableProcessor. Do not modify!")
                .build()

        // Write file with KSP dependencies attached for incremental compilation
        fileSpec.writeTo(
            codeGenerator,
            dependencies = Dependencies(true, *classes.mapNotNull { it.containingFile }.toTypedArray())
        )
        logger.info(
            "KotlinXSerializableProcessor: generated $packageName.$fileName for " +
                    classes.joinToString { it.qualifiedName?.asString() ?: it.simpleName.asString() }
        )
    }
}

class KotlinXSerializableProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return KotlinXSerializableProcessor(
            codeGenerator = environment.codeGenerator,
            logger = environment.logger,
            namespace = environment.options[OPTION_NAMESPACE] ?: DEFAULT_NAMESPACE
        )
    }

    private companion object {
        const val OPTION_NAMESPACE = "serializable.processor.namespace"
        const val DEFAULT_NAMESPACE = "generated"
    }
}